/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\syx_project\\OneDrive\\project\\vue-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-9c1f87c2",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c1f87c2").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-446b0893",
    path: "/articles/css-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-446b0893").then(next)
    },
  },
  {
    name: "v-e7ca8916",
    path: "/articles/git-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7ca8916").then(next)
    },
  },
  {
    name: "v-28249fe9",
    path: "/articles/js-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28249fe9").then(next)
    },
  },
  {
    name: "v-e05413e6",
    path: "/articles/vue-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e05413e6").then(next)
    },
  },
  {
    name: "v-5726ddbf",
    path: "/articles/xcx-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5726ddbf").then(next)
    },
  },
  {
    name: "v-9da04d9c",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9da04d9c").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-4217da8f",
    path: "/guide/bushu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4217da8f").then(next)
    },
  },
  {
    name: "v-cbbb23a2",
    path: "/guide/guide-about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cbbb23a2").then(next)
    },
  },
  {
    name: "v-0c43026f",
    path: "/guide/md-study.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c43026f").then(next)
    },
  },
  {
    name: "v-327aed2f",
    path: "/guide/vue-press-study.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-327aed2f").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]