/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "余温无痕个人博客",
  "description": "",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present 余温无痕"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9c1f87c2",
      "path": "/"
    },
    {
      "title": "CSS相关文章",
      "frontmatter": {},
      "regularPath": "/articles/css-about.html",
      "relativePath": "articles/css-about.md",
      "key": "v-446b0893",
      "path": "/articles/css-about.html"
    },
    {
      "title": "Git的注意点",
      "frontmatter": {},
      "regularPath": "/articles/git-about.html",
      "relativePath": "articles/git-about.md",
      "key": "v-e7ca8916",
      "path": "/articles/git-about.html",
      "headers": [
        {
          "level": 2,
          "title": "解决Git提交到GitHub，每次都要输入用户名和密码问题",
          "slug": "解决git提交到github-每次都要输入用户名和密码问题"
        }
      ]
    },
    {
      "title": "JS相关文章",
      "frontmatter": {},
      "regularPath": "/articles/js-about.html",
      "relativePath": "articles/js-about.md",
      "key": "v-28249fe9",
      "path": "/articles/js-about.html"
    },
    {
      "title": "Vue相关文章",
      "frontmatter": {},
      "regularPath": "/articles/vue-about.html",
      "relativePath": "articles/vue-about.md",
      "key": "v-e05413e6",
      "path": "/articles/vue-about.html"
    },
    {
      "title": "微信小程序相关文章",
      "frontmatter": {},
      "regularPath": "/articles/xcx-about.html",
      "relativePath": "articles/xcx-about.md",
      "key": "v-5726ddbf",
      "path": "/articles/xcx-about.html"
    },
    {
      "title": "前言",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-9da04d9c",
      "path": "/guide/"
    },
    {
      "title": "GitHub Pages 部署",
      "frontmatter": {},
      "regularPath": "/guide/bushu.html",
      "relativePath": "guide/bushu.md",
      "key": "v-4217da8f",
      "path": "/guide/bushu.html",
      "headers": [
        {
          "level": 2,
          "title": "前提（推荐使用 yarn）",
          "slug": "前提-推荐使用-yarn"
        },
        {
          "level": 2,
          "title": "开始部署",
          "slug": "开始部署"
        },
        {
          "level": 2,
          "title": "正式部署",
          "slug": "正式部署"
        }
      ]
    },
    {
      "title": "关于博主",
      "frontmatter": {},
      "regularPath": "/guide/guide-about.html",
      "relativePath": "guide/guide-about.md",
      "key": "v-cbbb23a2",
      "path": "/guide/guide-about.html"
    },
    {
      "title": "Markdown学习",
      "frontmatter": {},
      "regularPath": "/guide/md-study.html",
      "relativePath": "guide/md-study.md",
      "key": "v-0c43026f",
      "path": "/guide/md-study.html",
      "headers": [
        {
          "level": 2,
          "title": "标题",
          "slug": "标题"
        },
        {
          "level": 2,
          "title": "字体",
          "slug": "字体"
        },
        {
          "level": 3,
          "title": "字体大小",
          "slug": "字体大小"
        },
        {
          "level": 3,
          "title": "字体颜色",
          "slug": "字体颜色"
        },
        {
          "level": 3,
          "title": "字体背景色",
          "slug": "字体背景色"
        },
        {
          "level": 2,
          "title": "图片样式",
          "slug": "图片样式"
        },
        {
          "level": 3,
          "title": "插入图片",
          "slug": "插入图片"
        },
        {
          "level": 3,
          "title": "设置百分比",
          "slug": "设置百分比"
        },
        {
          "level": 3,
          "title": "设置固定大小",
          "slug": "设置固定大小"
        },
        {
          "level": 3,
          "title": "设置水平居中",
          "slug": "设置水平居中"
        },
        {
          "level": 2,
          "title": "段落换行",
          "slug": "段落换行"
        },
        {
          "level": 2,
          "title": "分隔线",
          "slug": "分隔线"
        },
        {
          "level": 2,
          "title": "Markdown 列表",
          "slug": "markdown-列表"
        },
        {
          "level": 2,
          "title": "区块",
          "slug": "区块"
        },
        {
          "level": 2,
          "title": "代码块中的语法高亮",
          "slug": "代码块中的语法高亮"
        },
        {
          "level": 2,
          "title": "代码块中的行高亮",
          "slug": "代码块中的行高亮"
        },
        {
          "level": 2,
          "title": "链接",
          "slug": "链接"
        },
        {
          "level": 2,
          "title": "自定义容器",
          "slug": "自定义容器"
        },
        {
          "level": 2,
          "title": "Emoji表情",
          "slug": "emoji表情"
        },
        {
          "level": 2,
          "title": "表格",
          "slug": "表格"
        },
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "行号",
          "slug": "行号"
        },
        {
          "level": 2,
          "title": "支持的 HTML 元素",
          "slug": "支持的-html-元素"
        },
        {
          "level": 2,
          "title": "转义",
          "slug": "转义"
        },
        {
          "level": 2,
          "title": "计算公式",
          "slug": "计算公式"
        }
      ]
    },
    {
      "title": "vuePress学习",
      "frontmatter": {},
      "regularPath": "/guide/vue-press-study.html",
      "relativePath": "guide/vue-press-study.md",
      "key": "v-327aed2f",
      "path": "/guide/vue-press-study.html",
      "headers": [
        {
          "level": 2,
          "title": "全局安装",
          "slug": "全局安装"
        },
        {
          "level": 2,
          "title": "局部安装（推荐）",
          "slug": "局部安装-推荐"
        },
        {
          "level": 3,
          "title": "创建项目",
          "slug": "创建项目"
        },
        {
          "level": 3,
          "title": "运行项目",
          "slug": "运行项目"
        },
        {
          "level": 2,
          "title": "项目配置",
          "slug": "项目配置"
        },
        {
          "level": 3,
          "title": "侧边栏导航配置",
          "slug": "侧边栏导航配置"
        },
        {
          "level": 3,
          "title": "首页配置",
          "slug": "首页配置"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://www.baidu.com"
      }
    ],
    "sidebarDepth": 2,
    "sidebar": [
      {
        "title": "指南",
        "collapsable": false,
        "children": [
          "/guide/",
          "/guide/guide-about",
          "/guide/md-study",
          "/guide/vue-press-study",
          "/guide/bushu"
        ]
      },
      {
        "title": "文章",
        "collapsable": false,
        "children": [
          "/articles/git-about",
          "/articles/vue-about",
          "/articles/xcx-about",
          "/articles/css-about",
          "/articles/js-about"
        ]
      }
    ]
  }
}